### ISSUE TITLE
[Bug]: Braze SDK 4+ does not work with Facebook SDK on iOS

### ISSUE THREAD

**Issue by indiecore** [braze-inc/braze-unity-sdk#102]
### Braze Unity SDK Version

4.0.0+

### Steps To Reproduce

Unity 2022.3.4f1
XCode 14.3.1

1. Create a new unity iOS product
2. Import latest Facebook Unity SDK (at time of writing this is 16.0.2 but have reproed with 16.0.0).
3. Test build, open in Xcode and build there (this build will succeed).
4. Add a Braze version 4+ to the unity project.
5. Enable (Automate Unity iOS Integration
6. Import SDWebImage Dependency
7. Make a new build, open in Xcode and build
8. This build will fail with the following error

`[project-directory]/Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityInterface.mm:288:59 Declaration of 'FBSDKShareBridgeOptionsDefault' must be imported from module 'FBSDKShareKit.FBSDKShareBridgeOptions' before it is required
`

Removing Braze SDK or using a version 3 variant builds successfully.

The Braze SDK is not compatible with the Facebook Unity SDK. This makes braze SDK 4+ essentially useless in a project if you require facebook integration as well.

The last active Braze version 3 is almost a year old at this point. Either Version 3 should get an update or this incompatibility should be addressed in Version 4.

---

Minimal Facebook Project
![minimalFacebookInt](https://github.com/braze-inc/braze-unity-sdk/assets/1449818/e26009de-c7b3-4f49-81a7-8cddce0f36f1)

Build succceeds
![buildSuccess](https://github.com/braze-inc/braze-unity-sdk/assets/1449818/02acefc1-9417-4656-945a-b55aa0ad73ef)

Add Braze
![Screenshot 2023-10-11 at 2 13 36 PM](https://github.com/braze-inc/braze-unity-sdk/assets/1449818/5c98078d-3e32-466e-86eb-d78f568a77a8)

Minimal FB + Braze fails
![fbFail](https://github.com/braze-inc/braze-unity-sdk/assets/1449818/cad0dd4f-4b1a-46db-a8f0-42ad5d496408)

### Expected Behavior

The SDK should not cause build failures on iOS when using the Facebook SDK.

### Actual Incorrect Behavior

Build fails with error message:

`[project-directory]/Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityInterface.mm:288:59 Declaration of 'FBSDKShareBridgeOptionsDefault' must be imported from module 'FBSDKShareKit.FBSDKShareBridgeOptions' before it is required
`

**Comment by hokstuff** [comment]
Hi @indiecore,

Thanks for raising this concern. We currently have an [open issue](https://github.com/braze-inc/braze-unity-sdk/issues/101) that you filed earlier around incompatibility with Xcode 14.3, which is related to the SDK not being compatible with ObjC++ files. This is because the [`-fcxx-modules` flag](https://github.com/braze-inc/braze-unity-sdk/blob/master/Assets/Plugins/Appboy/Editor/PostBuild.cs#L94) added to link the Braze SDK (which is imported via [`@import` syntax](https://clang.llvm.org/docs/Modules.html#objective-c-import-declaration)) was incompatible with one of Apple's changes when upgrading from Xcode 14.2 → 14.3.

I noticed that the [Facebook Unity SDK](https://github.com/facebook/facebook-sdk-for-unity/tree/main) includes ObjC++ `.mm` files, which conflicts with the Braze Unity SDK's settings. As we investigate a solution for the root cause, are you able to test with Xcode 14.2 to see if these errors are still present?

Thanks!

**Comment by indiecore** [comment]
Fails with the same error on 14.2

![Screenshot 2023-10-12 at 7 33 57 PM](https://github.com/braze-inc/braze-unity-sdk/assets/1449818/8921cd3e-1d6d-4d31-86f1-699a5e9e98a4)

**Comment by hokstuff** [comment]
Thank you for verifying that. We will investigate on our side. Until we are able to come up with a solution, please keep this thread updated if you are able to find any workarounds for `4.x` or have any suggestions around fixing this issue, given [our SDK is open sourced](https://github.com/braze-inc/braze-unity-sdk/tree/master/Assets/Plugins/Appboy).

Thanks!

**Comment by hokstuff** [comment]
Hi @indiecore,

Just checking another possibility - have you verified whether or not the Braze Unity SDK `4.x` is compatible with any version of the Facebook Unity SDK prior to version `16.0.0`? I'm trying to rule out whether or not there is a recent change on Facebook's SDK version(s) that may have brought an incompatibility as well. Thanks!

**Comment by hokstuff** [comment]
Hi @indiecore,

We have released [Unity SDK version 5.0.0](https://github.com/braze-inc/braze-unity-sdk/releases/tag/5.0.0) which addresses includes changes in related to [this issue](https://github.com/braze-inc/braze-unity-sdk/issues/101), and we have also verified locally that it is compatible with the Facebook SDK. Let us know if you run into any issues!

Thanks!
