### ISSUE TITLE
[Bug]: iOS Rich Push Notifications

### ISSUE THREAD

**Issue by idamaeng** [braze-inc/braze-unity-sdk#106]
### Braze Unity SDK Version

6.0.0

### Steps To Reproduce

- Create a XCode project out of your Unity project
- Follow these steps https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b2-rich-push-notifications
- Upload your build to testflight
- Send a test push including a image

### Expected Behavior

Receiving a push notification including the image.

### Actual Incorrect Behavior

Receiving a push notification without the image

**Comment by idamaeng** [comment]
Maybe its worth mentioning that I needed to rearrange the build phase of the main target to be able to build. Actually I moved Embed Frameworks and Embed Foundation Extension as high as possible

<img width="1128" alt="Screenshot 2024-06-13 at 18 06 01" src="https://github.com/braze-inc/braze-unity-sdk/assets/42933713/d5820cc5-686f-485d-bccf-ef7962e496f0">

**Comment by idamaeng** [comment]
Do you need further info?

**Comment by vanessaland** [comment]
Hi @idamaeng ,

Thanks for reaching out! Here are some things you can try:
- On the `Targets` > `NotificationService` configurations page, ensure that you are adding the `BrazeNotificationService` module under `General` > `Frameworks and Libraries`
- Ensure you have all the necessary components in your `NotificationService` class ([tutorial](https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b2-rich-push-notifications/))

If you are still experiencing this issue, can you please contact [support@braze.com](mailto:support@braze.com) with more information:

- Attach verbose logs when reproducing this issue
- Attach your code file/snippet for `NotificationService.swift`
- Attach a screenshot of your `Targets` > `NotificationService` configurations page
- Mention the Braze Unity SDK version you are on and which XCode version you are on 
- Add a link to this Github issue for reference

The Braze Support team should help with diagnosing the root cause of this issue! 

Thanks!

**Comment by idamaeng** [comment]
Thanks for the reply. You are referring to the steps I already tried. See the tutorial link I initially posted in my bug description :). Trying my luck with sending a mail to your support team.

**Comment by vanessaland** [comment]
Closing out this issue due to inactivity.

If you would need further assistance, feel free to reach out to our support team at [support@braze.com](mailto:support@braze.com).

Thank you!
